#pragma once

enum class eJoystickAxis
{
	LEFT_AXIS = 0,
	RIGHT_AXIS = 1,
};


enum eJoystickButton
{

	JOYSTICK_BUTTON_A = 0,
	JOYSTICK_BUTTON_B = 1,
	JOYSTICK_BUTTON_X = 2,
	JOYSTICK_BUTTON_Y = 3,
	JOYSTICK_BUTTON_LEFT_BUMPER = 4,
	JOYSTICK_BUTTON_RIGHT_BUMPER = 5,
	JOYSTICK_BUTTON_BACK = 6,
	JOYSTICK_BUTTON_START = 7,
	JOYSTICK_BUTTON_GUIDE = 8,
	JOYSTICK_BUTTON_LEFT_THUMB = 9,
	JOYSTICK_BUTTON_RIGHT_THUMB = 10,
	JOYSTICK_BUTTON_DPAD_UP = 11,
	JOYSTICK_BUTTON_DPAD_RIGHT = 12,
	JOYSTICK_BUTTON_DPAD_DOWN = 13,
	JOYSTICK_BUTTON_DPAD_LEFT = 14,

};

